import Head from 'next/head'
import { Roboto } from '@next/font/google'
import '../styles/globals.scss'
import Menu from './../components/Menu';
import NextNProgress from './../components/NextNProgress';
import LoadingScreen from './../components/LoadingScreen';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin']
})

function MyApp({ Component, pageProps }) {

  const [loading, setLoading] = useState(false);

  const router = useRouter();

  useEffect(() => {
    router.events.on("routeChangeStart", (url) => {
      setLoading(true);
    });

    router.events.on("routeChangeComplete", (url) => {
      setLoading(false);
    });

    router.events.on("routeChangeError", (url) => {
      setLoading(false);
    });

  }, [router])


  return <>
    <Head>
      <title>PFSRealty</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={roboto.className}>
      <Menu />
      <Component {...pageProps} />
      <NextNProgress />
      {
        loading
        &&
        <LoadingScreen />
      }
    </main>
  </>
}

export default MyApp
